sonar.projectKey=pipeline-test
sonar.projectName=Pipeline Test
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/__tests__/**/*
sonar.exclusions=src/__tests__/**/*
sonar.javascript.lcov.reportPaths=coverage/lcov.info
